[package]
name = "distrakt"
version = "0.1.0"
authors = ["Jens Gatzweiler <lichthagel@tuta.io>"]
edition = "2018"

[dependencies]
# change when released
trakt = { git = "https://github.com/Lichthagel/trakt-rust", rev = "5ab6d41" }
serenity = "0.5.11"
serde = "1.0.85"
serde_json = "1.0.36"
serde_derive = "1.0.85"
typemap = "0.3.3"